---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-internal-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-internal
  {{ end }}
{{ file .INGRESS_INTERNAL_ANNOTATIONS | indent 2 }}
spec:
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.internal.branch.sas-notprod.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - rod.internal.uat.sas-notprod.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
        - rod.internal.stg.sas.homeoffice.gov.uk
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-internal
      {{ else }}
      secretName: ingress-internal
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.internal.branch.sas-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: {{ .APP_NAME }}.internal.uat.sas-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
    - host: rod.internal.stg.sas.homeoffice.gov.uk
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
              {{ else }}
              serviceName: {{ .APP_NAME }}
              {{ end }}
              servicePort: 10443
